"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";

import { api, json } from "./api-client";
import {
  aiReviewProvenanceResponseSchema, aiReviewResponseSchema, aiReviewRunsResponseSchema, aiReviewTerminalResponseSchema,
  type AiRequirementReview, type AiReviewProvenance, type AiReviewWorkingSuggestion, type ScopeDraft,
} from "./api-schemas";
import { ConfirmDialog } from "./confirm-dialog";

function ErrorNote({ error }: { error: unknown }) {
  return error ? <p className="notice error" role="alert">{error instanceof Error ? error.message : "The quality review request could not be completed."}</p> : null;
}

function Value({ value }: Readonly<{ value: string | string[] }>) {
  return Array.isArray(value) ? <ol>{value.map((item, index) => <li className="plain-text" key={index}>{item}</li>)}</ol> : <p className="plain-text">{value}</p>;
}

function AppliedReviewHistory({ projectId, runs }: Readonly<{ projectId: string; runs: Array<{ id: string; appliedAt?: string; counts: { suggestions: number } }> }>) {
  const [provenance, setProvenance] = useState<AiReviewProvenance>();
  const [error, setError] = useState<unknown>();
  if (!runs.length) return null;
  return <section className="ai-history" aria-labelledby="quality-history-heading">
    <h5 id="quality-history-heading">Applied quality reviews</h5>
    <ul>{runs.map((run) => <li key={run.id}><span>{run.counts.suggestions} suggestions · {run.appliedAt ? new Date(run.appliedAt).toLocaleString() : "Applied"}</span> <button type="button" className="secondary compact" onClick={async () => { try { setError(undefined); setProvenance((await api(`/projects/${projectId}/ai/requirement-reviews/${run.id}/provenance`, {}, aiReviewProvenanceResponseSchema)).provenance); } catch (caught) { setError(caught); } }}>View provenance</button></li>)}</ul>
    <ErrorNote error={error} />
    {provenance && <article className="ai-provenance"><div className="panel-heading"><h5>Applied review provenance</h5><button type="button" className="secondary compact" onClick={() => setProvenance(undefined)}>Close</button></div><p className="fine">Generated by {provenance.initiatedBy.displayName}; applied by {provenance.appliedBy.displayName} on {new Date(provenance.appliedAt).toLocaleString()}.</p><details><summary>Reviewed draft snapshot</summary><ul>{provenance.canonicalInput.requirements.map((item) => <li key={item.logicalRequirementId}>{item.title}</li>)}</ul></details><details><summary>Original AI findings</summary><ul>{provenance.original.findings.map((item) => <li key={item.key}>{item.explanation}</li>)}</ul></details><details><summary>Final human-confirmed patches</summary><ul>{provenance.finalSelectedPatches.map((item, index) => <li key={`${item.targetRequirementId}-${index}`}>{item.kind.replaceAll("-", " ")}</li>)}</ul></details></article>}
  </section>;
}

function ReviewEditor({ projectId, initial, reloadDraft, close }: Readonly<{ projectId: string; initial: AiRequirementReview; reloadDraft: () => Promise<unknown>; close: () => void }>) {
  const queryClient = useQueryClient();
  const heading = useRef<HTMLHeadingElement>(null);
  const [review, setReview] = useState(initial);
  const [working, setWorking] = useState(initial.workingSuggestions ?? []);
  const [dirty, setDirty] = useState(false);
  const [confirmApply, setConfirmApply] = useState(false);
  const [message, setMessage] = useState<string>();
  useEffect(() => { heading.current?.focus(); }, []);
  const requirementNames = new Map(review.boundDraft.requirements.map((item) => [item.logicalRequirementId, item.title]));
  const findingByKey = new Map(review.original.findings.map((item) => [item.key, item]));
  const update = (key: string, patch: Partial<AiReviewWorkingSuggestion>) => {
    setWorking((items) => items.map((item) => item.key === key ? { ...item, ...patch } : item)); setDirty(true);
  };
  const save = useMutation({
    mutationFn: () => api(`/projects/${projectId}/ai/requirement-reviews/${review.id}`, json("PUT", {
      expectedReviewRevision: review.reviewRevision,
      suggestions: working.map((item) => ({ key: item.key, selected: item.selected, proposedValue: item.patch.proposedValue })),
    }), aiReviewResponseSchema),
    onSuccess: ({ review: next }) => { if ("freshness" in next) { setReview(next); setWorking(next.workingSuggestions ?? []); setDirty(false); setMessage("Staging changes saved."); } },
  });
  const discard = useMutation({
    mutationFn: () => api(`/projects/${projectId}/ai/requirement-reviews/${review.id}/discard`, json("POST", { expectedReviewRevision: review.reviewRevision, confirmed: true }), aiReviewTerminalResponseSchema),
    onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["ai-requirement-reviews", projectId] }); close(); },
  });
  const apply = useMutation({
    mutationFn: () => api(`/projects/${projectId}/ai/requirement-reviews/${review.id}/apply`, json("POST", {
      expectedReviewRevision: review.reviewRevision, expectedDraftRevision: review.binding.baseDraftRevision, confirmed: true,
    }), aiReviewResponseSchema),
    onSuccess: async () => { setConfirmApply(false); await Promise.all([reloadDraft(), queryClient.invalidateQueries({ queryKey: ["ai-requirement-reviews", projectId] })]); close(); },
  });
  const selectedCount = working.filter((item) => item.selected).length;
  const editable = review.actions.canEdit && review.freshness === "fresh";
  return <section className="ai-stage" aria-labelledby="quality-stage-heading">
    <div className="panel-heading"><div><p className="eyebrow">AI-assisted private staging</p><h5 id="quality-stage-heading" ref={heading} tabIndex={-1}>Review quality findings</h5></div><span className="badge">Advisory only</span></div>
    <p className="fine">The original review is immutable. Only explicitly selected, saved suggestions are applied, together or not at all.</p>
    {review.expiresAt && <p className="fine">Expires {new Date(review.expiresAt).toLocaleString()}.</p>}
    {review.freshness === "stale" && <p className="notice warning" role="status">The saved draft changed after this review. Findings remain readable, but suggestions cannot be edited or applied. Refresh and run a new review.</p>}
    {message && <p className="notice success" role="status">{message}</p>}<ErrorNote error={save.error || discard.error || apply.error} />
    {!review.original.findings.length && <p className="notice success" role="status">No material quality issues were found. There is nothing to apply.</p>}
    <div className="quality-findings">{review.original.findings.map((finding) => <article className="review-requirement" key={finding.key}>
      <p className="eyebrow">{finding.category.replaceAll("-", " ")}</p><h6>{requirementNames.get(finding.primaryRequirementId) ?? "Reviewed requirement"}</h6><p className="plain-text">{finding.explanation}</p>
      {finding.relatedRequirementIds?.length ? <p className="fine">Related: {finding.relatedRequirementIds.map((id) => requirementNames.get(id) ?? "Reviewed requirement").join(", ")}</p> : null}
    </article>)}</div>
    {working.length > 0 && <section aria-labelledby="quality-suggestions-heading"><h5 id="quality-suggestions-heading">Applyable suggestions</h5>{working.map((suggestion) => {
      const finding = findingByKey.get(suggestion.patch.findingKey);
      const proposed = suggestion.patch.proposedValue;
      return <fieldset className="requirement-editor" key={suggestion.key}><legend>{suggestion.patch.kind.replaceAll("-", " ")}</legend>
        <p className="fine">Target: {requirementNames.get(suggestion.patch.targetRequirementId)} · Finding: {finding?.category.replaceAll("-", " ")}</p><p>{suggestion.rationale}</p>
        <label className="check-row"><input type="checkbox" checked={suggestion.selected} disabled={!editable} onChange={(event) => update(suggestion.key, { selected: event.target.checked })} /> Select this suggestion</label>
        <div className="value-comparison"><div><strong>Expected current value</strong><Value value={suggestion.patch.expectedValue} /></div><div><strong>Proposed value</strong>{Array.isArray(proposed) ? <div className="criteria">{proposed.map((criterion, index) => <div className="criterion-row" key={index}><label><span className="sr-only">Proposed criterion {index + 1}</span><textarea rows={2} maxLength={2_000} disabled={!editable} value={criterion} onChange={(event) => update(suggestion.key, { patch: { ...suggestion.patch, proposedValue: proposed.map((item, itemIndex) => itemIndex === index ? event.target.value : item) } })} /></label><button type="button" className="danger compact" disabled={!editable || proposed.length === 1} onClick={() => update(suggestion.key, { patch: { ...suggestion.patch, proposedValue: proposed.filter((_, itemIndex) => itemIndex !== index) } })}>Remove</button></div>)}<button type="button" className="secondary compact" disabled={!editable || proposed.length >= 50} onClick={() => update(suggestion.key, { patch: { ...suggestion.patch, proposedValue: [...proposed, ""] } })}>Add criterion</button></div> : <label><span className="sr-only">Proposed text</span><textarea rows={4} maxLength={suggestion.patch.kind === "replace-title" ? 120 : 5_000} disabled={!editable} value={proposed} onChange={(event) => update(suggestion.key, { patch: { ...suggestion.patch, proposedValue: event.target.value } })} /></label>}</div></div>
      </fieldset>;
    })}</section>}
    {review.original.clarificationQuestions.length > 0 && <section className="ai-warnings" aria-labelledby="clarification-heading"><h5 id="clarification-heading">Clarification questions · not applyable</h5><p className="fine">Resolve missing information through ordinary human communication, then edit the draft manually.</p><ul>{review.original.clarificationQuestions.map((question, index) => <li key={`${question.findingKey}-${index}`}><strong>{question.requirementIds.map((id) => requirementNames.get(id)).filter(Boolean).join(", ")}</strong>: {question.question}</li>)}</ul></section>}
    {dirty && <p className="notice warning" role="status">Save staging changes before applying.</p>}
    <div className="row-actions"><button type="button" className="secondary" onClick={close}>Close</button><button type="button" className="danger" disabled={!review.actions.canDiscard || discard.isPending} onClick={() => discard.mutate()}>Discard review</button><button type="button" className="secondary" disabled={!dirty || !editable || save.isPending} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save staging"}</button><button type="button" className="primary" disabled={dirty || !review.actions.canApply || selectedCount === 0 || apply.isPending} onClick={() => setConfirmApply(true)}>Apply {selectedCount} selected</button></div>
    {confirmApply && <ConfirmDialog title={`Apply ${selectedCount} quality suggestions?`} description="All selected changes will be validated and applied atomically to this exact saved draft revision. No partial changes will be kept." confirmLabel="Apply selected changes" busy={apply.isPending} onCancel={() => setConfirmApply(false)} onConfirm={() => apply.mutate()} />}
  </section>;
}

export function AiRequirementReviewPanel({ projectId, draft, reloadDraft }: Readonly<{ projectId: string; draft: ScopeDraft; reloadDraft: () => Promise<unknown> }>) {
  const queryClient = useQueryClient();
  const [review, setReview] = useState<AiRequirementReview>();
  const [openDisclosure, setOpenDisclosure] = useState(false);
  const runs = useQuery({ queryKey: ["ai-requirement-reviews", projectId], queryFn: () => api(`/projects/${projectId}/ai/requirement-reviews`, {}, aiReviewRunsResponseSchema) });
  const generate = useMutation({
    mutationFn: () => api(`/projects/${projectId}/ai/requirement-reviews`, json("POST", { expectedDraftId: draft.id, expectedDraftRevision: draft.revisionToken }), aiReviewResponseSchema),
    onSuccess: async ({ review: next }) => { setOpenDisclosure(false); if ("freshness" in next) setReview(next); await queryClient.invalidateQueries({ queryKey: ["ai-requirement-reviews", projectId] }); },
  });
  const open = async (id: string) => { const next = (await api(`/projects/${projectId}/ai/requirement-reviews/${id}`, {}, aiReviewResponseSchema)).review; if ("freshness" in next) setReview(next); };
  if (runs.isPending) return <section className="ai-panel"><p role="status">Checking quality-review availability…</p></section>;
  if (runs.error) return <section className="ai-panel"><ErrorNote error={runs.error} /></section>;
  if (review) return <section className="ai-panel"><ReviewEditor projectId={projectId} initial={review} reloadDraft={reloadDraft} close={() => setReview(undefined)} /></section>;
  const pending = runs.data.runs.filter((run) => run.state === "pending-review");
  const applied = runs.data.runs.filter((run) => run.state === "applied");
  return <section className="ai-panel" aria-labelledby="quality-review-heading"><div className="panel-heading"><div><p className="eyebrow">Optional review aid</p><h4 id="quality-review-heading">Review requirement quality with AI</h4></div><span className="badge">Provider private</span></div>
    <p className="fine">Review the complete saved draft for vagueness, missing acceptance detail, conflicts, and questions. Manual editing remains available at all times.</p>
    {!runs.data.availability.enabled ? <p className="notice warning">AI quality review is unavailable. All manual requirement controls remain available.</p> : <button type="button" className="secondary" disabled={!draft.requirements.length} onClick={() => setOpenDisclosure(true)}>Review saved draft</button>}
    <ErrorNote error={generate.error} />
    {pending.length > 0 && <section><h5>Review in progress</h5><ul>{pending.map((run) => <li key={run.id}><span>{run.counts.findings} findings · {run.freshness}{run.expiresAt ? ` · expires ${new Date(run.expiresAt).toLocaleString()}` : ""}</span> <button type="button" className="secondary compact" onClick={() => void open(run.id)}>Open review</button></li>)}</ul></section>}
    <AppliedReviewHistory projectId={projectId} runs={applied} />
    <p className="fine">Quality review shares the limit of 10 admitted AI requirement requests per rolling hour with AI structuring. Drafts over 256 KiB are rejected before provider contact.</p>
    {openDisclosure && <ConfirmDialog title="Send this saved draft for AI quality review?" description="Only ordered group labels and requirement IDs, titles, descriptions, and acceptance criteria are sent to the configured AI provider. Findings are advisory, private to authorized providers, and cannot change the draft until you explicitly apply selected suggestions." confirmLabel={generate.isPending ? "Reviewing…" : "Generate private review"} busy={generate.isPending} onCancel={() => setOpenDisclosure(false)} onConfirm={() => generate.mutate()} />}
  </section>;
}
