"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";

import { api, json } from "./api-client";
import {
  aiProposalResponseSchema, aiProvenanceResponseSchema, aiRunsResponseSchema, aiTerminalProposalResponseSchema,
  type AiPendingProposal, type AiProvenance, type AiWorkingProposal, type ScopeDraft,
} from "./api-schemas";
import { ConfirmDialog } from "./confirm-dialog";

function move<T>(items: T[], index: number, direction: -1 | 1): T[] {
  const destination = index + direction;
  if (destination < 0 || destination >= items.length) return items;
  const next = [...items]; [next[index], next[destination]] = [next[destination]!, next[index]!]; return next;
}

function ErrorNote({ error }: { error: unknown }) {
  return error ? <p className="notice error" role="alert">{error instanceof Error ? error.message : "The AI request could not be completed."}</p> : null;
}

function AppliedRuns({ projectId, runs }: Readonly<{ projectId: string; runs: Array<{ id: string; appliedAt?: string; initiatedBy: { displayName: string }; counts: { requirements: number } }> }>) {
  const [detail, setDetail] = useState<AiProvenance>();
  const [error, setError] = useState<unknown>();
  if (!runs.length) return null;
  return <section className="ai-history" aria-labelledby="ai-history-heading">
    <h4 id="ai-history-heading">Applied AI imports</h4>
    <ul>{runs.map((run) => <li key={run.id}><span>{run.counts.requirements} requirements · {run.initiatedBy.displayName}{run.appliedAt ? ` · ${new Date(run.appliedAt).toLocaleString()}` : ""}</span> <button type="button" className="secondary compact" onClick={async () => { try { setError(undefined); setDetail((await api(`/projects/${projectId}/ai/requirement-proposals/${run.id}/provenance`, {}, aiProvenanceResponseSchema)).provenance); } catch (caught) { setError(caught); } }}>View provenance</button></li>)}</ul>
    <ErrorNote error={error} />
    {detail && <article className="ai-provenance"><div className="panel-heading"><h5>Applied import provenance</h5><button type="button" className="secondary compact" onClick={() => setDetail(undefined)}>Close</button></div><p className="fine">Generated by {detail.initiatedBy.displayName}; applied by {detail.appliedBy.displayName} on {new Date(detail.appliedAt).toLocaleString()}.</p><details><summary>Original private source</summary><pre className="plain-text ai-source-preview">{detail.rawSource}</pre></details><details><summary>Original AI output</summary><ul>{detail.original.requirements.map((item) => <li key={item.key}>{item.title}</li>)}</ul></details><details><summary>Final human-confirmed selection</summary><ul>{detail.finalSelection.requirements.map((item) => <li key={item.key}>{item.title}</li>)}</ul></details></article>}
  </section>;
}

function ProposalEditor({ projectId, initial, onClosed, onApplied }: Readonly<{ projectId: string; initial: AiPendingProposal; onClosed: () => void; onApplied: () => Promise<unknown> }>) {
  const queryClient = useQueryClient();
  const heading = useRef<HTMLHeadingElement>(null);
  const [proposal, setProposal] = useState(initial);
  const [working, setWorking] = useState<AiWorkingProposal>(initial.working);
  const [dirty, setDirty] = useState(false);
  const [confirmApply, setConfirmApply] = useState(false);
  const [message, setMessage] = useState<string>();
  useEffect(() => { heading.current?.focus(); }, []);
  const updateRequirement = (index: number, patch: Partial<AiWorkingProposal["requirements"][number]>) => {
    setWorking((value) => ({ ...value, requirements: value.requirements.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })); setDirty(true);
  };
  const save = useMutation({
    mutationFn: () => api(`/projects/${projectId}/ai/requirement-proposals/${proposal.id}`, json("PUT", { expectedProposalRevision: proposal.proposalRevision, working }), aiProposalResponseSchema),
    onSuccess: ({ proposal: next }) => { if (next.state === "pending") { setProposal(next); setWorking(next.working); setDirty(false); setMessage("Staging changes saved."); } },
  });
  const discard = useMutation({
    mutationFn: () => api(`/projects/${projectId}/ai/requirement-proposals/${proposal.id}/discard`, json("POST", { expectedProposalRevision: proposal.proposalRevision, confirmed: true }), aiTerminalProposalResponseSchema),
    onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["ai-requirement-runs", projectId] }); onClosed(); },
  });
  const apply = useMutation({
    mutationFn: () => {
      const requirements = proposal.working.requirements.filter((item) => item.selected).map((item) => ({
        key: item.key, ...(item.groupKey ? { groupKey: item.groupKey } : {}), title: item.title,
        description: item.description, acceptanceCriteria: item.acceptanceCriteria,
      }));
      const used = new Set(requirements.flatMap((item) => item.groupKey ? [item.groupKey] : []));
      const groups = proposal.working.groups.filter((item) => used.has(item.key));
      return api(`/projects/${projectId}/ai/requirement-proposals/${proposal.id}/apply`, json("POST", {
        expectedProposalRevision: proposal.proposalRevision, expectedDraftRevision: proposal.binding.baseDraftRevision,
        selection: { groups, requirements }, confirmed: true,
      }), aiProposalResponseSchema);
    },
    onSuccess: async () => { setConfirmApply(false); await Promise.all([onApplied(), queryClient.invalidateQueries({ queryKey: ["ai-requirement-runs", projectId] })]); onClosed(); },
  });
  const selectedCount = working.requirements.filter((item) => item.selected).length;
  return <section className="ai-stage" aria-labelledby="ai-stage-heading">
    <div className="panel-heading"><div><p className="eyebrow">AI-assisted private staging</p><h4 id="ai-stage-heading" ref={heading} tabIndex={-1}>Review before adding to the draft</h4></div><span className="badge">Not yet in scope</span></div>
    <p className="fine">Expires {new Date(proposal.expiresAt).toLocaleString()}. AI warnings are guidance, not commitments.</p>
    {message && <p className="notice success" role="status">{message}</p>}<ErrorNote error={save.error || discard.error || apply.error} />
    <details><summary>Compare original private source</summary><pre className="plain-text ai-source-preview">{proposal.rawSource}</pre></details>
    {proposal.warnings.length > 0 && <section className="ai-warnings" aria-labelledby="ai-warnings-heading"><h5 id="ai-warnings-heading">Grounding warnings</h5><ul>{proposal.warnings.map((warning, index) => <li key={`${warning.category}-${index}`}><strong>{warning.category.replaceAll("-", " ")}</strong>: {warning.message}</li>)}</ul></section>}
    <div className="scope-section"><h5>Proposed groups</h5>{working.groups.map((group, index) => <div className="draft-row" key={group.key}><label>Group {index + 1}<input maxLength={120} disabled={!proposal.actions.canEdit} value={group.name} onChange={(event) => { setWorking((value) => ({ ...value, groups: value.groups.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item) })); setDirty(true); }} /></label><div className="row-actions"><button type="button" className="secondary compact" disabled={index === 0 || !proposal.actions.canEdit} onClick={() => { setWorking((value) => ({ ...value, groups: move(value.groups, index, -1) })); setDirty(true); }}>Move up</button><button type="button" className="secondary compact" disabled={index === working.groups.length - 1 || !proposal.actions.canEdit} onClick={() => { setWorking((value) => ({ ...value, groups: move(value.groups, index, 1) })); setDirty(true); }}>Move down</button><button type="button" className="danger compact" disabled={!proposal.actions.canEdit || working.requirements.some((item) => item.groupKey === group.key)} onClick={() => { setWorking((value) => ({ ...value, groups: value.groups.filter((item) => item.key !== group.key) })); setDirty(true); }}>Remove</button></div></div>)}</div>
    <div className="scope-section"><h5>Proposed requirements</h5>{working.requirements.map((requirement, index) => <fieldset className="requirement-editor" key={requirement.key}><legend>Requirement {index + 1}</legend><label className="check-row"><input type="checkbox" disabled={!proposal.actions.canEdit} checked={requirement.selected} onChange={(event) => updateRequirement(index, { selected: event.target.checked })} /> Include when applied</label><label>Title<input maxLength={120} disabled={!proposal.actions.canEdit} value={requirement.title} onChange={(event) => updateRequirement(index, { title: event.target.value })} /></label><label>Description<textarea rows={3} maxLength={5_000} disabled={!proposal.actions.canEdit} value={requirement.description} onChange={(event) => updateRequirement(index, { description: event.target.value })} /></label><label>Group<select disabled={!proposal.actions.canEdit} value={requirement.groupKey ?? ""} onChange={(event) => updateRequirement(index, { groupKey: event.target.value || undefined })}><option value="">Ungrouped</option>{working.groups.map((group) => <option key={group.key} value={group.key}>{group.name}</option>)}</select></label><div className="criteria"><span>Acceptance criteria</span>{requirement.acceptanceCriteria.map((criterion, criterionIndex) => <div className="criterion-row" key={criterionIndex}><label><span className="sr-only">Criterion {criterionIndex + 1}</span><textarea rows={2} maxLength={2_000} disabled={!proposal.actions.canEdit} value={criterion} onChange={(event) => updateRequirement(index, { acceptanceCriteria: requirement.acceptanceCriteria.map((item, itemIndex) => itemIndex === criterionIndex ? event.target.value : item) })} /></label><button type="button" className="danger compact" disabled={!proposal.actions.canEdit || requirement.acceptanceCriteria.length === 1} onClick={() => updateRequirement(index, { acceptanceCriteria: requirement.acceptanceCriteria.filter((_, itemIndex) => itemIndex !== criterionIndex) })}>Remove criterion</button></div>)}<button type="button" className="secondary compact" disabled={!proposal.actions.canEdit || requirement.acceptanceCriteria.length >= 50} onClick={() => updateRequirement(index, { acceptanceCriteria: [...requirement.acceptanceCriteria, ""] })}>Add criterion</button></div><div className="row-actions"><button type="button" className="secondary compact" disabled={!proposal.actions.canEdit || index === 0} onClick={() => { setWorking((value) => ({ ...value, requirements: move(value.requirements, index, -1) })); setDirty(true); }}>Move up</button><button type="button" className="secondary compact" disabled={!proposal.actions.canEdit || index === working.requirements.length - 1} onClick={() => { setWorking((value) => ({ ...value, requirements: move(value.requirements, index, 1) })); setDirty(true); }}>Move down</button></div></fieldset>)}</div>
    {dirty && <p className="notice warning" role="status">Save staging changes before applying.</p>}
    <div className="row-actions"><button type="button" className="danger" disabled={!proposal.actions.canDiscard || discard.isPending} onClick={() => discard.mutate()}>Discard proposal</button><button type="button" className="secondary" disabled={!dirty || save.isPending || !proposal.actions.canEdit} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save staging"}</button><button type="button" className="primary" disabled={dirty || !proposal.actions.canApply || selectedCount === 0 || apply.isPending} onClick={() => setConfirmApply(true)}>Apply {selectedCount} selected</button></div>
    {confirmApply && <ConfirmDialog title="Append selected requirements?" description="This appends the selected items to the current requirement draft. Existing groups and requirements will not be changed." confirmLabel="Append to draft" busy={apply.isPending} onCancel={() => setConfirmApply(false)} onConfirm={() => apply.mutate()} />}
  </section>;
}

export function AiRequirementPanel({ projectId, draft, reloadDraft }: Readonly<{ projectId: string; draft: ScopeDraft; reloadDraft: () => Promise<unknown> }>) {
  const queryClient = useQueryClient();
  const [source, setSource] = useState("");
  const [proposal, setProposal] = useState<AiPendingProposal>();
  const runs = useQuery({ queryKey: ["ai-requirement-runs", projectId], queryFn: () => api(`/projects/${projectId}/ai/requirement-proposals`, {}, aiRunsResponseSchema) });
  const generate = useMutation({
    mutationFn: () => api(`/projects/${projectId}/ai/requirement-proposals`, json("POST", { source }), aiProposalResponseSchema),
    onSuccess: async ({ proposal: next }) => { if (next.state === "pending") { setProposal(next); await queryClient.invalidateQueries({ queryKey: ["ai-requirement-runs", projectId] }); } },
  });
  const open = async (id: string) => { const result = await api(`/projects/${projectId}/ai/requirement-proposals/${id}`, {}, aiProposalResponseSchema); if (result.proposal.state === "pending") setProposal(result.proposal); };
  if (runs.isPending) return <section className="ai-panel"><p role="status">Checking AI availability…</p></section>;
  if (runs.error) return <section className="ai-panel"><ErrorNote error={runs.error} /></section>;
  if (proposal) return <section className="ai-panel"><ProposalEditor projectId={projectId} initial={proposal} onClosed={() => setProposal(undefined)} onApplied={reloadDraft} /></section>;
  const pending = runs.data.runs.filter((run) => run.state === "pending");
  const applied = runs.data.runs.filter((run) => run.state === "applied");
  return <section className="ai-panel" aria-labelledby="ai-heading"><div className="panel-heading"><div><p className="eyebrow">Optional authoring aid</p><h4 id="ai-heading">Structure notes with AI</h4></div><span className="badge">Provider private</span></div>
    <p className="fine">Pasted text is sent to the configured AI provider. It is private to authorized providers and never changes this draft until you review and explicitly apply selected items.</p>
    {!runs.data.availability.enabled ? <p className="notice warning">AI structuring is unavailable. All manual requirement controls remain available.</p> : <form onSubmit={(event) => { event.preventDefault(); generate.mutate(); }}><label>Messy requirement notes<textarea rows={7} maxLength={20_000} required value={source} onChange={(event) => setSource(event.target.value)} aria-describedby="ai-source-count" /></label><p id="ai-source-count" className="fine">{source.length.toLocaleString()} / 20,000 characters</p><button className="secondary" disabled={generate.isPending || !source.trim()}>{generate.isPending ? "Structuring…" : "Generate private proposal"}</button></form>}
    <ErrorNote error={generate.error} />
    {pending.length > 0 && <section><h5>Pending proposals</h5><ul>{pending.map((run) => <li key={run.id}><span>{run.counts.requirements} requirements · expires {new Date(run.expiresAt).toLocaleString()}</span> <button type="button" className="secondary compact" onClick={() => void open(run.id)}>Review</button></li>)}</ul></section>}
    <AppliedRuns projectId={projectId} runs={applied} />
    <p className="fine">Current draft capacity: {50 - draft.groups.length} groups and {200 - draft.requirements.length} requirements.</p>
  </section>;
}
