/* eslint-disable @next/next/no-html-link-for-pages -- Public navigation intentionally supports no-client-navigation fallback. */
import { ArrowRight, ArrowUpRight, Check, CheckCheck, FileCheck2, GitPullRequest, History, Layers3, LockKeyhole, ShieldCheck } from "lucide-react";
import { publicMedia } from "./public-media";
import { PublicImage } from "./public-image";

export const sourceUrl = "https://github.com/shahzaibalijamro/client-scope";
export function PublicBrand() {
  return <a className="public-brand" href="/" aria-label="ClientScope home"><span className="brand-mark" aria-hidden="true">C</span><span>Client<span>Scope</span></span></a>;
}
function SourceLink() { return <a href={sourceUrl} target="_blank" rel="noopener noreferrer">View source <ArrowUpRight size={15} aria-hidden="true" /><span className="sr-only"> (opens in a new tab)</span></a>; }
function EntryActions() {
  return <div className="public-actions"><a className="primary" href="/sign-in?intent=demo">Explore demo <ArrowRight size={17} aria-hidden="true" /></a><a className="public-secondary" href="/sign-up">Create account <ArrowUpRight size={15} aria-hidden="true" /></a></div>;
}
const stories = [
  { label: "01 / AGREE", title: "A clear starting point. A record that stays.", text: "Turn requirements into an explicit agreement. Review the details together, capture the decision, and keep the approved version visible.", icon: FileCheck2 },
  { label: "02 / ADAPT", title: "Change the scope. Keep the context.", text: "Make additions and tradeoffs visible through formal change requests. Compare the proposal, record the decision, and preserve the original agreement.", icon: GitPullRequest },
  { label: "03 / DELIVER", title: "Every revision brings you closer.", text: "Share deliverables, collect feedback, and submit a new version. Know what was reviewed, what needs revision, and what the client approved.", icon: Layers3 },
];
export function PublicHome() {
  return <div className="public-page">
    <a className="public-skip" href="#main-content">Skip to content</a>
    <header className="public-header"><PublicBrand /><nav aria-label="Public navigation"><a href="#workflow">How it works</a><a href="#product">The product</a><a href="/sign-in" className="public-signin">Sign in <ArrowUpRight size={15} aria-hidden="true" /></a></nav></header>
    <main id="main-content" tabIndex={-1}>
      <section className="public-hero" aria-labelledby="hero-title">
        <div className="public-hero-copy"><p className="public-kicker"><span aria-hidden="true" /> THE CLIENT AGREEMENT, IN ONE PLACE</p><h1 id="hero-title">Clear work.<br /><span>Clear decisions.</span></h1><p className="public-lead">From the first “can you build this?” to the final approval. Keep scope, changes, and delivery in one shared record.</p><EntryActions /><p className="public-caption">For freelancers and small service teams.<br />Built for the person on the other side of the project, too.</p></div>
        <div className="public-hero-art" aria-label="Illustrated project agreement showing scope, review, and approval">
          <div className="public-orbit" aria-hidden="true" /><div className="public-proof-card"><div className="public-proof-top"><span className="public-dot-grid" aria-hidden="true">⠿</span><span>THE SHARED RECORD</span><LockKeyhole size={15} aria-hidden="true" /></div><div className="public-proof-body"><p className="eyebrow">Website project · Illustrative example</p><h2>Same page.<br />Every step.</h2><ol><li><span className="proof-icon"><FileCheck2 size={18} aria-hidden="true" /></span><div><strong>Scope agreed</strong><small>Requirements & acceptance criteria</small></div><Check size={16} aria-hidden="true" /></li><li><span className="proof-icon"><GitPullRequest size={18} aria-hidden="true" /></span><div><strong>Change recorded</strong><small>A decision with its context</small></div><Check size={16} aria-hidden="true" /></li><li><span className="proof-icon"><Layers3 size={18} aria-hidden="true" /></span><div><strong>Delivery in review</strong><small>The current version, ready to review</small></div><span className="proof-wait">Now</span></li></ol><div className="public-proof-footer"><History size={15} aria-hidden="true" /> One story. Nothing lost between versions.</div></div></div><div className="public-approval-chip"><CheckCheck size={20} aria-hidden="true" /><div><strong>People make the decisions.</strong><span>ClientScope keeps the record.</span></div></div>
        </div>
      </section>
      <section className="public-problem public-section" aria-labelledby="problem-title"><p className="public-kicker">LESS CHASING. MORE CLARITY.</p><div><h2 id="problem-title">The agreement shouldn’t live<br />in five different conversations.</h2><p>Requirements in a document. Changes in a message. An approval buried in email. ClientScope gives you and your client a shared place to answer: what did we agree, what changed, and what needs a decision?</p></div></section>
      <section className="public-section public-workflow" id="workflow" aria-labelledby="workflow-title"><div className="public-section-heading"><p className="public-kicker">A SIMPLE WAY THROUGH</p><h2 id="workflow-title">From “let’s do it”<br />to “looks good.”</h2><p>Your client-facing workflow, without an internal task board getting in the way.</p></div><ol className="public-workflow-steps">{[{ title: "Define & agree", text: "Structure the requirements. Get an explicit client decision." }, { title: "Track & adapt", text: "Share milestone progress. Review changes before they become scope." }, { title: "Review & revise", text: "Submit work. Keep feedback connected to the version reviewed." }, { title: "Approve & preserve", text: "Confirm completion. Keep decisions and history available." }].map((step, index) => <li key={step.title}><span className="public-step-number">0{index + 1}</span><h3>{step.title}</h3><p>{step.text}</p></li>)}</ol></section>
      <section className="public-section public-stories" id="product" aria-labelledby="product-title"><div className="public-section-heading"><p className="public-kicker">THE PRODUCT, IN PRACTICE</p><h2 id="product-title">Less guesswork.<br />A better shared record.</h2></div>{stories.map((story, index) => <article className="public-story" key={story.label}><div className="public-story-copy"><span className="public-story-icon"><story.icon size={24} aria-hidden="true" /></span><p className="public-kicker">{story.label}</p><h3>{story.title}</h3><p>{story.text}</p></div><PublicImage media={publicMedia[index]} /></article>)}</section>
      <section className="public-section public-trust" aria-labelledby="trust-title"><div className="public-section-heading"><p className="public-kicker">CONFIDENCE COMES FROM CLARITY</p><h2 id="trust-title">Human decisions.<br />A dependable history.</h2></div><div className="public-trust-grid"><article><ShieldCheck aria-hidden="true" /><h3>Authority is explicit</h3><p>Participation and approval are different roles. Only an authorized client approver can make a binding workflow decision.</p></article><article><History aria-hidden="true" /><h3>Decisions stay visible</h3><p>Approved versions and significant actions remain part of the story. New work adds context instead of rewriting past agreements.</p></article><article><LockKeyhole aria-hidden="true" /><h3>Private by default</h3><p>Workspace and project access is checked by the API. People see the work their current membership permits.</p></article><article><Layers3 aria-hidden="true" /><h3>AI assists. You decide.</h3><p>Structure requirements, spot ambiguity, and summarize feedback. Human confirmation stays essential; manual workflows stay available.</p></article></div></section>
      <section className="public-section public-engineering" aria-labelledby="engineering-title"><div><p className="public-kicker">BUILT WITH INTENT</p><h2 id="engineering-title">Small-team focus.<br />Visible engineering.</h2><p>A TypeScript application with a Next.js interface, an Express API, and MongoDB. Specifications, tests, and delivery checks make the implementation open to inspection.</p><div className="public-tech-list"><span>Contextual authorization</span><span>Versioned records</span><span>Automated workflow tests</span><span>CI-gated delivery</span></div><SourceLink /></div><aside aria-label="Demo and availability limitations"><p className="public-kicker">A NOTE BEFORE YOU EXPLORE</p><h3>A real workflow.<br />A shared portfolio demo.</h3><p>The demo is shared and resettable. Changes are temporary, so use it to explore with synthetic information.</p><p>ClientScope runs at portfolio/demo scale on managed services with free-tier constraints. Availability can vary. It is not enterprise infrastructure, legal evidence, or a compliance-grade audit system.</p><p>Create your own account for a separate workspace under the same portfolio-scale availability limits.</p></aside></section>
      <section className="public-final public-section" aria-labelledby="final-title"><p className="public-kicker">GET ON THE SAME PAGE</p><h2 id="final-title">Make the next decision<br />a clear one.</h2><EntryActions /><a className="public-returning" href="/sign-in">Already have an account? Sign in</a></section>
    </main>
    <footer className="public-footer"><PublicBrand /><p>Clear work. Clear decisions.</p><nav aria-label="Footer"><SourceLink /><a href="/sign-up">Create account</a><a href="/sign-in">Sign in</a></nav></footer>
  </div>;
}
