import { expect, type Browser, type Page, test } from "@playwright/test";

const password = "correct horse battery staple"; const origin = "http://127.0.0.1:4200";
async function account(browser: Browser, email: string, displayName: string) {
  const context = await browser.newContext(); const page = await context.newPage(); await page.goto("/"); await page.getByRole("button", { name: "Create account" }).click();
  await page.getByLabel("Display name").fill(displayName); await page.getByLabel("Email address").fill(email); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Create account" }).click();
  let text = ""; await expect.poll(async () => { const response = await page.request.get(`/api/v1/test/emails?to=${encodeURIComponent(email)}&category=verification`); if (response.ok()) text = ((await response.json()) as { text: string }).text; return response.status(); }).toBe(200);
  const link = text.match(/https?:\/\/\S+/u)?.[0]; if (!link) throw new Error("Verification link missing"); await page.goto(link); await page.getByRole("button", { name: "Verify email" }).click(); await page.getByRole("link", { name: "Continue to ClientScope" }).click(); return { context, page, email };
}
async function mutate<T>(page: Page, method: "POST" | "PUT", path: string, data: unknown): Promise<T> {
  const csrf = await (await page.request.get("/api/v1/csrf")).json() as { csrfToken: string }; const response = await page.request.fetch(`/api/v1${path}`, { method, data, headers: { Origin: origin, "X-CSRF-Token": csrf.csrfToken } });
  if (!response.ok()) throw new Error(`${method} ${path} failed: ${response.status()} ${await response.text()}`); return response.json() as Promise<T>;
}
async function openProject(page: Page, name: string) { await page.goto("/"); await page.getByRole("button", { name: new RegExp(name) }).click(); await expect(page.getByRole("heading", { name: "Deliverables and review" })).toBeVisible(); }

test("provider generates a grounded private summary and sees deterministic outdatedness", async ({ browser }) => {
  test.slow(); const key = Date.now(); const owner = await account(browser, `summary-owner-${key}@example.com`, "Owner"); const participant = await account(browser, `summary-participant-${key}@example.com`, "Participant"); const approver = await account(browser, `summary-approver-${key}@example.com`, "Approver");
  const workspace = await mutate<{ workspace: { id: string } }>(owner.page, "POST", "/workspaces", { name: `Summary Studio ${key}` }); const client = await mutate<{ client: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/clients`, { name: "Summary Client" }); const projectName = `Summary Project ${key}`; const project = await mutate<{ project: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/projects`, { clientId: client.client.id, name: projectName });
  for (const [target, role] of [[participant, "client-participant"], [approver, "client-approver"]] as const) { const invite = await mutate<{ invitation: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/invitations`, { kind: "project", projectId: project.project.id, email: target.email, role }); await mutate(target.page, "POST", `/invitations/${invite.invitation.id}/accept`, {}); }
  const scopeDraft = await mutate<{ draft: { revisionToken: string } }>(owner.page, "POST", `/projects/${project.project.id}/scope/draft`, {}); const savedScope = await mutate<{ draft: { revisionToken: string } }>(owner.page, "PUT", `/projects/${project.project.id}/scope/draft`, { revisionToken: scopeDraft.draft.revisionToken, groups: [], requirements: [{ title: "Website", description: "Build the agreed website.", acceptanceCriteria: ["Ready for review"], order: 0 }] }); const scopeVersion = await mutate<{ version: { id: string } }>(owner.page, "POST", `/projects/${project.project.id}/scope/submissions`, { revisionToken: savedScope.draft.revisionToken, confirmed: true }); await mutate(approver.page, "POST", `/projects/${project.project.id}/scope/versions/${scopeVersion.version.id}/decisions`, { outcome: "approved", confirmed: true });
  const created = await mutate<{ deliverable: { id: string; draft: { revisionToken: string } } }>(owner.page, "POST", `/projects/${project.project.id}/deliverables`, { title: "Homepage package" }); const deliverableId = created.deliverable.id;
  const saved = await mutate<{ deliverable: { draft: { revisionToken: string } } }>(owner.page, "PUT", `/projects/${project.project.id}/deliverables/${deliverableId}/draft`, { revisionToken: created.deliverable.draft.revisionToken, notes: "Review responsive layout.", revisionSummary: "", links: [{ id: "507f1f77bcf86cd799439011", label: "Preview", url: "https://example.com/", order: 0 }], attachmentIds: [] });
  const submitted = await mutate<{ version: { id: string } }>(owner.page, "POST", `/projects/${project.project.id}/deliverables/${deliverableId}/submissions`, { revisionToken: saved.deliverable.draft.revisionToken, confirmed: true });
  const comment = await mutate<{ comment: { id: string } }>(participant.page, "POST", `/projects/${project.project.id}/deliverables/${deliverableId}/versions/${submitted.version.id}/comments`, { body: "Increase mobile spacing around the call to action." });
  await mutate(approver.page, "POST", `/projects/${project.project.id}/deliverables/${deliverableId}/versions/${submitted.version.id}/comments`, { body: "Keep the desktop rhythm compact." });
  await mutate(approver.page, "POST", `/projects/${project.project.id}/deliverables/${deliverableId}/versions/${submitted.version.id}/decisions`, { outcome: "changes-requested", note: "Make the mobile controls easier to tap.", confirmed: true });

  await openProject(owner.page, projectName); await owner.page.setViewportSize({ width: 390, height: 844 }); const card = owner.page.locator(".deliverable-card", { hasText: "Homepage package" });
  await card.getByRole("button", { name: "Generate summary" }).click(); const disclosure = owner.page.getByRole("dialog", { name: "Generate a private feedback summary?" }); await expect(disclosure).toContainText("Only eligible client-authored comments and formal revision-request notes"); await disclosure.getByRole("button", { name: "Generate summary" }).click();
  await expect(card.getByRole("heading", { name: "Summarize client feedback" })).toBeFocused(); await expect(card.getByRole("heading", { name: "Themes" })).toBeVisible(); await expect(card.getByRole("heading", { name: "Requested actions" })).toBeVisible(); await expect(card.getByRole("heading", { name: "Tensions or unclear points" })).toBeVisible(); await expect(card.getByText(comment.comment.id).first()).toBeVisible();
  expect(await owner.page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await openProject(participant.page, projectName); await expect(participant.page.getByRole("heading", { name: "Summarize client feedback" })).not.toBeVisible();

  const collection = await (await owner.page.request.get(`/api/v1/projects/${project.project.id}/deliverables`)).json() as { deliverables: { deliverables: Array<{ id: string; draft?: { revisionToken: string; links: unknown[]; attachments: Array<{ id: string }> } }> } }; const draft = collection.deliverables.deliverables.find((item) => item.id === deliverableId)!.draft!;
  const revised = await mutate<{ deliverable: { draft: { revisionToken: string } } }>(owner.page, "PUT", `/projects/${project.project.id}/deliverables/${deliverableId}/draft`, { revisionToken: draft.revisionToken, notes: "Review responsive layout.", revisionSummary: "Improved mobile spacing.", links: draft.links, attachmentIds: draft.attachments.map((item) => item.id) }); const versionTwo = await mutate<{ version: { id: string } }>(owner.page, "POST", `/projects/${project.project.id}/deliverables/${deliverableId}/submissions`, { revisionToken: revised.deliverable.draft.revisionToken, confirmed: true }); await mutate(participant.page, "POST", `/projects/${project.project.id}/deliverables/${deliverableId}/versions/${versionTwo.version.id}/comments`, { body: "The new mobile spacing is clearer." });
  await openProject(owner.page, projectName); await expect(owner.page.locator(".deliverable-card", { hasText: "Homepage package" }).getByText("outdated", { exact: true })).toBeVisible(); await expect(owner.page.getByText(/only explicit regeneration can replace it/i)).toBeVisible();
  await Promise.all([owner.context.close(), participant.context.close(), approver.context.close()]);
});
