import { expect, type Browser, type Page, test } from "@playwright/test";

const password = "correct horse battery staple"; const origin = "http://127.0.0.1:4200";
async function account(browser: Browser, email: string, displayName: string, mobile = false) {
  const context = await browser.newContext(mobile ? { viewport: { width: 390, height: 844 } } : undefined); const page = await context.newPage(); await page.goto("/"); await page.getByRole("button", { name: "Create account" }).click();
  await page.getByLabel("Display name").fill(displayName); await page.getByLabel("Email address").fill(email); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Create account" }).click();
  let text = ""; await expect.poll(async () => { const response = await page.request.get(`/api/v1/test/emails?to=${encodeURIComponent(email)}&category=verification`); if (response.ok()) text = ((await response.json()) as { text: string }).text; return response.status(); }).toBe(200);
  const link = text.match(/https?:\/\/\S+/u)?.[0]; if (!link) throw new Error("Verification link missing"); await page.goto(link); await page.getByRole("button", { name: "Verify email" }).click(); await page.getByRole("link", { name: "Continue to ClientScope" }).click(); return { context, page, email };
}
async function mutate<T>(page: Page, method: "POST" | "PUT", path: string, data: unknown): Promise<T> { const csrf = await (await page.request.get("/api/v1/csrf")).json() as { csrfToken: string }; const response = await page.request.fetch(`/api/v1${path}`, { method, data, headers: { Origin: origin, "X-CSRF-Token": csrf.csrfToken } }); if (!response.ok()) throw new Error(`${method} ${path} failed: ${response.status()} ${await response.text()}`); return response.json() as Promise<T>; }
async function openProject(page: Page, name: string) { await page.goto("/"); await page.getByRole("button", { name: new RegExp(name) }).click(); await expect(page.getByRole("heading", { name: "Deliverables and review" })).toBeVisible(); }

test("link deliverable moves through participant feedback, revision, resubmission, and approval", async ({ browser }) => {
  test.slow(); const key = Date.now(); const owner = await account(browser, `deliverable-owner-${key}@example.com`, "Owner"); const participant = await account(browser, `deliverable-participant-${key}@example.com`, "Participant", true); const approver = await account(browser, `deliverable-approver-${key}@example.com`, "Approver", true);
  const workspace = await mutate<{ workspace: { id: string } }>(owner.page, "POST", "/workspaces", { name: `Studio ${key}` }); const client = await mutate<{ client: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/clients`, { name: `Client ${key}` }); const projectName = `Delivery ${key}`; const project = await mutate<{ project: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/projects`, { clientId: client.client.id, name: projectName });
  for (const [target, role] of [[participant, "client-participant"], [approver, "client-approver"]] as const) { const invite = await mutate<{ invitation: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/invitations`, { kind: "project", projectId: project.project.id, email: target.email, role }); await mutate(target.page, "POST", `/invitations/${invite.invitation.id}/accept`, {}); }
  const scopeDraft = await mutate<{ draft: { revisionToken: string } }>(owner.page, "POST", `/projects/${project.project.id}/scope/draft`, {}); const filledScope = await mutate<{ draft: { revisionToken: string } }>(owner.page, "PUT", `/projects/${project.project.id}/scope/draft`, { revisionToken: scopeDraft.draft.revisionToken, groups: [], requirements: [{ title: "Website", description: "Build the agreed website.", acceptanceCriteria: ["Ready for review"], order: 0 }] }); const scopeVersion = await mutate<{ version: { id: string } }>(owner.page, "POST", `/projects/${project.project.id}/scope/submissions`, { revisionToken: filledScope.draft.revisionToken, confirmed: true }); await mutate(approver.page, "POST", `/projects/${project.project.id}/scope/versions/${scopeVersion.version.id}/decisions`, { outcome: "approved", confirmed: true });

  await openProject(owner.page, projectName); const create = owner.page.locator(".deliverable-create"); await create.getByLabel("Deliverable title").fill("Homepage package"); await create.getByRole("button", { name: "Create draft" }).click(); const card = owner.page.locator(".deliverable-card", { hasText: "Homepage package" }); await expect(card.getByText("Provider-private draft", { exact: false })).toBeVisible(); await card.getByRole("button", { name: "Add link" }).click(); await card.getByLabel("Link label").fill("Staging homepage"); await card.getByLabel("HTTPS address").fill("https://example.com/staging"); await card.getByLabel("Version notes (optional)").fill("Review the responsive homepage."); await card.getByRole("button", { name: "Save draft details" }).click(); await expect(card.getByText("Draft saved.")).toBeVisible(); await card.getByRole("button", { name: "Submit version 1" }).click(); await expect(card.locator(".deliverable-card-heading .deliverable-status")).toHaveText("in review");

  await openProject(participant.page, projectName); const participantCard = participant.page.locator(".deliverable-card", { hasText: "Homepage package" }); await expect(participantCard.getByText("Provider-private draft", { exact: false })).not.toBeVisible(); await participantCard.getByLabel("Comment").fill("Increase mobile spacing around the call to action."); await participantCard.getByRole("button", { name: "Post comment" }).click(); await expect(participantCard.getByText("Increase mobile spacing around the call to action.")).toBeVisible(); await expect(participantCard.getByRole("button", { name: "Approve exact version" })).not.toBeVisible(); expect(await participant.page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);

  await openProject(approver.page, projectName); const approverCard = approver.page.locator(".deliverable-card", { hasText: "Homepage package" }); await approverCard.getByRole("button", { name: "Request revision" }).click(); await approver.page.getByLabel("Required revision").fill("Increase the mobile spacing and resubmit."); await approver.page.getByRole("button", { name: "Request revision", exact: true }).last().click(); await expect(approverCard.getByText("revision draft", { exact: true })).toBeVisible();

  await openProject(owner.page, projectName); const revision = owner.page.locator(".deliverable-card", { hasText: "Homepage package" }); await expect(revision.getByLabel("Revision summary")).toBeVisible(); await revision.getByLabel("Revision summary").fill("Increased mobile spacing."); await revision.getByRole("button", { name: "Save draft details" }).click(); await expect(revision.getByText("Draft saved.")).toBeVisible(); await revision.getByRole("button", { name: "Submit revised version" }).click(); await expect(revision.getByText("Version 2")).toBeVisible();
  await openProject(approver.page, projectName); const finalReview = approver.page.locator(".deliverable-card", { hasText: "Homepage package" }); await finalReview.getByRole("button", { name: "Approve exact version" }).click(); await approver.page.getByLabel("Approval note (optional)").fill("Ready to ship."); await approver.page.getByRole("button", { name: "Approve version" }).click(); await expect(approver.page.locator(".terminal-deliverable", { hasText: "Homepage package" })).toContainText("approved");
  await approver.page.getByRole("button", { name: "Show version history" }).last().click(); await expect(approver.page.getByText("Increase mobile spacing around the call to action.")).toBeVisible(); await expect(approver.page.getByText("Increased mobile spacing.")).toBeVisible();
  await Promise.all([owner.context.close(), participant.context.close(), approver.context.close()]);
});
