import { expect, type Browser, type Page, test } from "@playwright/test";

const password = "correct horse battery staple"; const origin = "http://127.0.0.1:4200";
async function account(browser: Browser, email: string, displayName: string) {
  const context = await browser.newContext(); const page = await context.newPage(); await page.goto("/"); await page.getByRole("button", { name: "Create account" }).click();
  await page.getByLabel("Display name").fill(displayName); await page.getByLabel("Email address").fill(email); await page.getByLabel("Password").fill(password); await page.getByRole("button", { name: "Create account" }).click();
  let text = ""; await expect.poll(async () => { const response = await page.request.get(`/api/v1/test/emails?to=${encodeURIComponent(email)}&category=verification`); if (response.ok()) text = ((await response.json()) as { text: string }).text; return response.status(); }).toBe(200);
  const link = text.match(/https?:\/\/\S+/u)?.[0]; if (!link) throw new Error("Verification link missing"); await page.goto(link); await page.getByRole("button", { name: "Verify email" }).click(); await page.getByRole("link", { name: "Continue to ClientScope" }).click(); return { context, page, email };
}
async function mutate<T>(page: Page, method: "POST" | "PUT", path: string, data: unknown): Promise<T> {
  const csrf = await (await page.request.get("/api/v1/csrf")).json() as { csrfToken: string };
  const response = await page.request.fetch(`/api/v1${path}`, { method, data, headers: { Origin: origin, "X-CSRF-Token": csrf.csrfToken } });
  if (!response.ok()) throw new Error(`${method} ${path} failed: ${response.status()} ${await response.text()}`); return response.json() as Promise<T>;
}
async function openProject(page: Page, name: string) { await page.goto("/"); await page.getByRole("button", { name: new RegExp(name) }).click(); await expect(page.getByRole("heading", { name: "Completion and record" })).toBeVisible(); }

test("final review permanently completes, archives, and restores the project record", async ({ browser }) => {
  test.slow(); const key = Date.now(); const owner = await account(browser, `completion-owner-${key}@example.com`, "Owner"); const approver = await account(browser, `completion-approver-${key}@example.com`, "Approver");
  const workspace = await mutate<{ workspace: { id: string } }>(owner.page, "POST", "/workspaces", { name: `Studio ${key}` }); const client = await mutate<{ client: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/clients`, { name: `Client ${key}` }); const projectName = `Completion ${key}`; const project = await mutate<{ project: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/projects`, { clientId: client.client.id, name: projectName });
  const invite = await mutate<{ invitation: { id: string } }>(owner.page, "POST", `/workspaces/${workspace.workspace.id}/invitations`, { kind: "project", projectId: project.project.id, email: approver.email, role: "client-approver" }); await mutate(approver.page, "POST", `/invitations/${invite.invitation.id}/accept`, {});
  const scopeDraft = await mutate<{ draft: { revisionToken: string } }>(owner.page, "POST", `/projects/${project.project.id}/scope/draft`, {}); const savedScope = await mutate<{ draft: { revisionToken: string } }>(owner.page, "PUT", `/projects/${project.project.id}/scope/draft`, { revisionToken: scopeDraft.draft.revisionToken, groups: [], requirements: [{ title: "Launch", description: "Complete the approved launch package.", acceptanceCriteria: ["Approved by the client"], order: 0 }] }); const scope = await mutate<{ version: { id: string } }>(owner.page, "POST", `/projects/${project.project.id}/scope/submissions`, { revisionToken: savedScope.draft.revisionToken, confirmed: true }); await mutate(approver.page, "POST", `/projects/${project.project.id}/scope/versions/${scope.version.id}/decisions`, { outcome: "approved", confirmed: true });
  const delivery = await mutate<{ deliverable: { id: string; draft: { revisionToken: string } } }>(owner.page, "POST", `/projects/${project.project.id}/deliverables`, { title: "Launch package" }); const linkId = "507f1f77bcf86cd799439011"; const savedDelivery = await mutate<{ deliverable: { draft: { revisionToken: string } } }>(owner.page, "PUT", `/projects/${project.project.id}/deliverables/${delivery.deliverable.id}/draft`, { revisionToken: delivery.deliverable.draft.revisionToken, notes: "Final launch", links: [{ id: linkId, label: "Launch", url: "https://example.com/launch", order: 0 }], attachmentIds: [] }); const submitted = await mutate<{ version: { id: string } }>(owner.page, "POST", `/projects/${project.project.id}/deliverables/${delivery.deliverable.id}/submissions`, { revisionToken: savedDelivery.deliverable.draft.revisionToken, confirmed: true }); await mutate(approver.page, "POST", `/projects/${project.project.id}/deliverables/${delivery.deliverable.id}/versions/${submitted.version.id}/decisions`, { confirmed: true, outcome: "approved", note: "Accepted" });

  await openProject(owner.page, projectName); await expect(owner.page.getByRole("heading", { name: "Ready for final review" })).toBeVisible(); await owner.page.getByRole("button", { name: "Request final review" }).click(); await owner.page.getByLabel("Optional summary").fill("All approved work is ready."); await owner.page.getByRole("button", { name: "Request final review" }).last().click(); await expect(owner.page.getByText("Project work is locked while final review is pending.")).toBeVisible();
  await openProject(approver.page, projectName); await approver.page.getByRole("button", { name: "Approve completion" }).click(); await approver.page.getByLabel("Optional note").fill("Final acceptance confirmed."); await approver.page.getByRole("button", { name: "Approve completion" }).last().click(); await expect(approver.page.getByText("This project is permanently read-only.")).toBeVisible();
  await openProject(owner.page, projectName); await owner.page.getByRole("button", { name: "Archive project" }).click(); await owner.page.getByLabel("Reason").fill("Move into project records."); await owner.page.getByRole("button", { name: "Archive project" }).last().click(); await expect(owner.page.locator(".lifecycle-panel > .panel-heading .badge")).toHaveText("archived"); await owner.page.getByRole("button", { name: "Restore to completed" }).click(); await owner.page.getByLabel("Reason").fill("Keep the record visible."); await owner.page.getByRole("button", { name: "Restore to completed" }).last().click(); await expect(owner.page.locator(".lifecycle-panel > .panel-heading .badge")).toHaveText("completed");
  await Promise.all([owner.context.close(), approver.context.close()]);
});
